version: '3'

services:
  web:
    build: 
     context: .
    ports:
      - "5000:5000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - todo-net

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - todo-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

networks:
  todo-net:

